#!/bin/bash
for file in $(find . -type f -name "*.gif"); do
    # استخدم parameter expansion فقط لإزالة المسار وامتداد .gif
    name="${file##*/}"   # إزالة المسار
    echo "${name%.gif}"  # إزالة الامتداد
done | sort -f
